### ISSUE TITLE
[bug] connect(ConnectType.CHROME_EXTENSION) not working

### ISSUE THREAD

**Issue by shahzaibatzeeyotech** [terra-money/wallet-provider#10]
Hi, i'm calling connect(ConnectType.CHROME_EXTENSION) function but noting happend. however connect(ConnectType.WALLETCONNECT) is working fine.

i also installed terra station extension and setup a wallet

**Comment by iamssen** [comment]
Did you check availableConnectTypes before call connect()?

**Comment by iamssen** [comment]
https://github.com/terra-money/wallet-provider/blob/2d7a92900cb23dfcce8347d99cbd35deca62644e/templates/create-react-app/src/components/ConnectSample.tsx#L38 Please refer this link

**Comment by shahzaibatzeeyotech** [comment]
yup i checked availableConnectTypes. 

`availableConnectTypes.includes(ConnectType.WEBEXTENSION)
        ? {
            label: "Terra Station Extension",
            image: <Terra {...size} />,
            onClick: () => connect(ConnectType.WEBEXTENSION),
          }
        : availableConnectTypes.includes(ConnectType.CHROME_EXTENSION)
        ? {
            label: "Terra Station Extension",
            image: <Terra {...size} />,
            onClick: () => connect(ConnectType.CHROME_EXTENSION),
          }
        : []`

**Comment by iamssen** [comment]
@shahzaibatzeeyotech Hmm... could you check your version? (version of `~/node_modules/@terra-money/wallet-provider/package.json`) if the version is not latest (1.2.2) update first please.

and, if you have web link (or repo) please show me. I can't estimate the cause.

**Comment by shahzaibatzeeyotech** [comment]
i tried with version 1.2.2. still issue is same

**Comment by iamssen** [comment]
I can't help you without the details. (Error message or source code) Try running this example first and see how it differs from your app.

https://github.com/terra-money/wallet-provider/tree/main/templates/create-react-app

**Comment by shahzaibatzeeyotech** [comment]
https://github.com/shahzaibatzeeyotech/wallet-provider-connct-bug-sample.git please review this sample
