### ISSUE TITLE
connect method not working

### ISSUE THREAD

**Issue by shahzaibatzeeyotech** [terra-money/wallet-provider#11]
previous discussion #10 

https://github.com/shahzaibatzeeyotech/wallet-provider-connct-bug-sample.git

 please review this sample

**Comment by iamssen** [comment]
![image](https://user-images.githubusercontent.com/357619/127812533-e5b68a0c-6ebf-4528-a15d-96b433f41f3d.png)

@shahzaibatzeeyotech Your sample can't build

**Comment by shahzaibatzeeyotech** [comment]
@iamssen i mentioned in readme.md this code is not working code this is just a sample. because actual project is private currently

**Comment by shahzaibatzeeyotech** [comment]
i implemented as it is but something went wrong with connect method of library

**Comment by shahzaibatzeeyotech** [comment]
Thanks @iamssen @hanjukim  . i just run `npm update`
