### ISSUE TITLE
Replace deprecated process.browser check

### ISSUE THREAD

**Issue by zlace0x** [terra-money/wallet-provider#12]
https://github.com/terra-money/wallet-provider/blob/5de98b6bf38ba6991de3be2cc3394b5cc0a3e640/templates/next/pages/_app.tsx#L41

the [suggested](https://github.com/vercel/next.js/pull/7651) way to check for client rendering
`typeof window !== "undefined"`

**Comment by iamssen** [comment]
@zlace0x good tip! thanks!
