### ISSUE TITLE
Get result of Tx (e.g. for uploading contract)?

### ISSUE THREAD

**Issue by dakom** [terra-money/wallet-provider#23]
The flow from the terra.js docs is something like this for uploading a contract

What would be the equivalent using `post()` or any other of the provider methods, so that I can get the final result back?

```
//returns a Promise<string> containing the contract code id if successful
function upload_contract(bytes) {
  const storeCode = new MsgStoreCode(wallet.key.accAddress, bytes);
  return wallet.createAndSignTx({ msgs: [storeCode], })
    .then(storeCodeTx => terra.tx.broadcast(storeCodeTx))
    .then(storeCodeTxResult => {
        if (isTxError(storeCodeTxResult)) {
          return Promise.reject(`store code failed. code: ${storeCodeTxResult.code}, codespace: ${storeCodeTxResult.codespace}, raw_log: ${storeCodeTxResult.raw_log}`);
        }

        const {
          store_code: { code_id },
        } = storeCodeTxResult.logs[0].eventsByType;

        return Promise.resolve(code_id[0]);
    });
}
```

**Comment by dakom** [comment]
Is this not possible, because the extension itself uses `sync` instead of `block`? : https://github.com/terra-money/station/blob/9064625093f352b1e8d65a44cfb81ef98e2775ce/src/extension/Confirm.tsx#L116

**Comment by dakom** [comment]
ok, I think I'm supposed to lookup the hash info after - but when I do `lcd.tx.txInfo(res.result.txhash)` I get a `404`

however, if I delay it by several seconds, then it works.

is this a bug? or is there some way to tell `wallet.post()` to wait until the block is resolved?

**Comment by iamssen** [comment]
@dakom After you broadcast Tx, it takes time for it to be processed as a block.

It will be a `txhash` value after `post()`. We tend to wait for the block to be processed by polling `txInfo()` at regular intervals of 500ms to 1000ms based on the corresponding txhash.

**Comment by dakom** [comment]
Thanks @iamssen !

I'm happy to share my "hello world" sorta project once I have it working... I'm moving the wallet integration stuff into its own iframe so that could help it be a nice reference since the core functions will be totally abstracted.

Closing the issue :)
