### ISSUE TITLE
Bombay Network Connection

### ISSUE THREAD

**Issue by Ruborcalor** [terra-money/wallet-provider#27]
The docs say:

"The network rules passed by the Terra Station Mobile are 0 is testnet, 1 is mainnet.

Always set testnet for 0 and mainnet for 1."

What do we do if we want to use bombay?

**Comment by iamssen** [comment]
@Ruborcalor The station mobile is still dropping network information only with mainnet=1 and testnet=0. We started working on modifying this. I'll let you know when the work is done.

**Comment by Ruborcalor** [comment]
Gotcha so this is a bug with terra station mobile and not wallet-provider?

**Comment by iamssen** [comment]
@Ruborcalor This problem has been resolved by updating Terra Station Mobile. 

<https://github.com/terra-money/wallet-provider#important-notice-for-columnus-5>

Please refer to this link and use wallet-provider. The bombay network will be recognized normally.

**Comment by Ruborcalor** [comment]
Cool thanks!
