### ISSUE TITLE
Use a different mainnet node

### ISSUE THREAD

**Issue by lubert** [terra-money/wallet-provider#33]
Hi, I'm trying to use a different mainnet network instead of the public node. What I'm trying is changing the `lcd` field to a different url in the options passed to the `WalletProvider`, however the terra station extension doesn't appear to respect the changes and still uses `lcd.terra.dev` when I'm inspecting network requests. Is it possible to change the node used by Terra Station programmatically?

**Comment by iamssen** [comment]
@lubert Please declare your custom network. Wallet-provider will follow the network settings you declared. You cannot change the properties of the mainnet that has already been declared.
![image](https://user-images.githubusercontent.com/357619/137050763-2d6a70c3-4ebc-40b9-ade5-5b5c0fbe250a.png)
