### ISSUE TITLE
Distribute bundled/minified js

### ISSUE THREAD

**Issue by josh-burton** [terra-money/wallet-provider#34]
Would be possible to distribute a bundled/minified version of the lib, like terra.js?

```
<script
  crossorigin
  src="https://unpkg.com/@terra-money/terra.js/dist/bundle.js"
></script>
```

**Comment by iamssen** [comment]
@josh-burton No, we will only provide installation using npm. Providing bundled js creates unnecessary difficulties because it requires a lot of dependencies, including RxJs and React. 

Because it is a high-level API library, it is designed based on Transpiler and Module system.
