### ISSUE TITLE
[feature] Export Connector which is used to connect to the wallet from @walletconnect library

### ISSUE THREAD

**Issue by Mskalba** [terra-money/wallet-provider#4]
useWallet hook give as access to some of the functionalities from @walletconnet, for example connect and disconnect functions.

We would like to have whole Connector class exported from @walletconnect library.

`class Connector implements IConnector`

We need that for example to use 

`signMessage(params: any[]): Promise<any>;`

**Comment by iamssen** [comment]
@Mskalba Sorry, the sign feature is not yet implemented for Terra Station Mobile and `@terra-money/wallet-provider`.

I am currently developing another service, so it will take time to implement the sign function. I will let you know again when the function is implemented.

**Comment by tkowalczyk** [comment]
@iamssen thank you for quick update, I am working with @Mskalba we have also tried some workarounds but without results as you might see here: https://github.com/terra-money/terra.js/issues/95, could you maybe provide some ETA for this feature?

**Comment by iamssen** [comment]
@tkowalczyk I'm sorry. I have a lot of things to develop, so it will be difficult to start development for this quickly.

I will discuss the development schedule for this part with the team.

**Comment by tkowalczyk** [comment]
fully understand, would be great if you will provide later some ETA, good luck!

**Comment by cryptoethic** [comment]
Hi!

As you have a lot of things in your pipeline, @iamssen, I would like to ask if you could utilize any help with this feature. 
If you could point out which libraries require changes so I could focus on extending them to provide such functionality. 

As far as I understand **signMessage** is not exported by useWallet, because it lacks implementation in Wallets (Terra Station Mobile only?)

Please let me know if you could give me some hints. What is missing in current version and where to look for it so I could have easier start with working on that ;)

**Comment by iamssen** [comment]
Started adding sign() feature. You can refer to this PR(https://github.com/terra-money/wallet-provider/pull/7).

We need to add features to the Mobile App, so it will take some time for the full release.

For now, you can test it based on Chrome Extension.

**Comment by iamssen** [comment]
We discussed and decided not to implement the sign() function in wallet-provider.

In the case of Extension, the sign() function is not a big threat because it is only within the user device, but sending a signed key through the walletconnect bridge server is considered a security concern.

**Comment by cryptoethic** [comment]
Oh, this is definitively a bad news.

Could I ask what dangers are introduced when we send signed transaction over walletconnect bridge? And how far it is different from creating a signed transaction via walletconnect and broadcasting it to the network.

I might be asking basic questions but I'm new to terra ecosystem and would love to gain as much knowledge as possible ;)
