### ISSUE TITLE
Signing a transaction fails

### ISSUE THREAD

**Issue by Ruborcalor** [terra-money/wallet-provider#40]
Hello there!

Today `connectedWallet.sign` started failing for me without any changes to my code.

![image](https://user-images.githubusercontent.com/47014480/138099789-b314b315-cbba-4658-8804-0260eb348c8e.png)

Is this due to a breaking change in the chrome extension? Any advice for how to resolve this?

**Comment by iamssen** [comment]
@Ruborcalor Yes, it is said that the Station extension with breaking change has been published.

Sorry. We had to deal with breaking change more carefully.

`terra.js@2.1` contains many breaking changes. (You can think of it as major update because the API changes significantly)

As a result, wallet-provider, station extension, and station mobile, which depend on terra.js, are likely to have many breaking changes. 

Please refer to the links below.

- Please use terra.js 2.1.x `npm install @terra-money/terra.js@beta`
- Please use wallet-provider 2.4.0-alpha.2 `npm install @terra-money/wallet-provider@next`
    - PR https://github.com/terra-money/wallet-provider/pull/39
    - `sign()` method sample https://github.com/terra-money/wallet-provider/blob/feature%2Fterrajs21/packages/src/components/SignSample.tsx#L52

**Comment by Ruborcalor** [comment]
Ignore that, I tried a different terra wallet and it seems to work now!

**Comment by iamssen** [comment]
https://github.com/terra-money/station/pull/198 It's being solved.

**Comment by borbier** [comment]
I've tried signing message in CodeSandbox demo (the Next.js) one and there's still an error occurred. Here is the message that was prompted

```
Error 
Unknown Error: Cannot read properties of undefined (reading 'chain_id')

Sign Message
{
  "fee": "{\"amount\":[{\"amount\":\"200000\",\"denom\":\"uusd\"}],\"gas\":\"1000000\"}",
  "msgs": [
    "{\"type\":\"bank/MsgSend\",\"value\":{\"amount\":[{\"amount\":\"1000000\",\"denom\":\"uusd\"}],\"from_address\":\"terra1n4gdmdqpwffkjm46h6edss6hq6l5eemtcqt95l\",\"to_address\":\"terra12hnhh5vtyg5juqnzm43970nh4fw42pt27nw9g9\"}}"
  ],
  "result": {
    "auth_info": {
      "fee": {
        "amount": [
          {
            "amount": "200000",
            "denom": "uusd"
          }
        ],
        "gas_limit": "1000000",
        "granter": "",
        "payer": ""
      },
      "signer_infos": [
        {
          "mode_info": {
            "single": {
              "mode": "SIGN_MODE_DIRECT"
            }
          },
          "public_key": {
            "@type": "/cosmos.crypto.secp256k1.PubKey",
            "key": "Apzo58HUJl8CJsFPt10eeYyWSb60CjUkcVYlfC/e7xtR"
          },
          "sequence": "7"
        }
      ]
    },
    "body": {
      "memo": "",
      "messages": [
        {
          "@type": "/cosmos.bank.v1beta1.MsgSend",
          "amount": [
            {
              "amount": "1000000",
              "denom": "uusd"
            }
          ],
          "from_address": "terra1n4gdmdqpwffkjm46h6edss6hq6l5eemtcqt95l",
          "to_address": "terra12hnhh5vtyg5juqnzm43970nh4fw42pt27nw9g9"
        }
      ],
      "timeout_height": "0"
    },
    "signatures": [
      "Hq5I913jMWbGFLb/UVJzXZDedMLhAgXnTx81BWsl74xCtukfsL15B8ZB6nkNDHPfIRxjIK5bfEc2nnVrm7mm0w=="
    ]
  },
  "success": true
}
```

**Comment by iamssen** [comment]
@borbier Currently, Station extension uses terra.js 2.1.x. So, the result of the `sign()` returned by the station extension will not be processed by terra.js 2.0.

Terra.js 3.x will be updated soon. This problem will be solved by that time.

Refer to the link below for an example of the changed `sign()`.

https://github.com/terra-money/wallet-provider/blob/feature%2Fterrajs21/packages/src/components/SignSample.tsx#L63

**Comment by Ruborcalor** [comment]
Do you have an example of how to verify a signed transaction?

**Comment by iamssen** [comment]
I updated the sample code for this. You can use the result of sign() by referring to the code on this link.

<https://github.com/terra-money/wallet-provider/blob/main/packages/src/components/SignSample.tsx#L67>
