### ISSUE TITLE
Use default export for bowser getParser

### ISSUE THREAD

**Issue by zlace** [terra-money/wallet-provider#5]
Bowser only exports a default export.

https://github.com/lancedikson/bowser/issues/458

This causes snowpack or vite build tools to fail in pre-bundling.

**Comment by iamssen** [comment]
@zlace Thank you for this issue report.

I just released `v1.2.1`.

I checked that my project using vite.js works without any problems. I don't use snowpack, so if there is any problem, please report the issue again.
