### ISSUE TITLE
`signBytes` seems to hang on ledger

### ISSUE THREAD

**Issue by Ruborcalor** [terra-money/wallet-provider#51]
When using `signBytes` with a ledger wallet, the terra station extension shows that it is broadcasting a transaction and the ledger doesn't seem to be prompted for anything:
![image](https://user-images.githubusercontent.com/47014480/145927194-ae50be0e-2bb6-4528-aa80-5860004ec24b.png)

Will ledger be supported for `signBytes`?

**Comment by iamssen** [comment]
I tried to find a way to do `ecdsaSign()` through Ledger, but I couldn't find a way. Ledger does not support `signBytes()` yet.

This is likely to be an error. I will inform the developer.

Thanks.

**Comment by Ruborcalor** [comment]
Okay cool thank you. Is there a way to tell from wallet provider whether or not the connected wallet is a ledger device?

**Comment by iamssen** [comment]
Unfortunately, there is no way to check whether the wallet is ledger in the wallet-provider because all extensions are not providing that information at this moment. In situations where this information can be checked, I will provide it through information such as availableSignBytes. There is no way at this moment.

**Comment by EugeneTeu** [comment]
hello, @Ruborcalor was wondering if u found a workaround for this issue? currently ran into the same issue with `signBytes()`

**Comment by Ruborcalor** [comment]
Hey @EugeneTeu , no good workaround for this right now. I opened a different issue https://github.com/terra-money/wallet-provider/issues/55 which when resolved will provide a solution for signing bytes via Ledger, but even then you won't be able to sign bytes from mobile.
