### ISSUE TITLE
CRITICAL BUG ISSUE - BREAKS WALLET POST MESSAGE.

### ISSUE THREAD

**Issue by NikitosGolubev** [terra-money/wallet-provider#62]
**Because typeof is forgotten,** posting transactions and getting TXHash result is no longer possible. That really breaks flow.

https://github.com/terra-money/wallet-provider/blob/5804e8f2bb087f834b933f2ac6e8dbb28ddda9a6/packages/src/%40terra-money/wallet-controller/modules/legacy-extension/createFixedExtension.ts#L88

```
function isValidResult({ error, ...payload }: any): boolean {
  if (payload.success !== 'boolean') { // FORGOT TYPEOF
    return false;
  } else if (
    typeof payload.result === 'undefined' &&
    typeof error === 'undefined'
  ) {
    return false;
  }
  return true;
}
```

The proposition to avoid such scenarios: After this update, running simple ```yarn``` command updated the dependencies and caused our application to break. We suggest using proper versioning, so things like this could have been easily revertable (would have been nice, if update here would have been versioned as wallet-provider 3.6.1.)
Plus, we recommend start practicing PR reviews.

Thank you for attention, please fix this bug as soon as possible :)
**TeFiLuck team relies on you guys, _as well as many more applications on Terra._**

**Comment by RomainLanz** [comment]
Why not providing a PR that fix the code, you will have a faster fix?

**Comment by iamssen** [comment]
Thanks for reporting. I'll publish fix version in few minutes.

**Comment by NikitosGolubev** [comment]
Thank you very much guys!
TeFiLuck team thanks you for such a quick response.
LFG!

**Comment by iamssen** [comment]
<https://www.npmjs.com/package/@terra-money/wallet-provider>

Fixed. please use `@terra-money/wallet-controller@^3.6.5` and `@terra-money/wallet-provider@^3.6.5`
