### ISSUE TITLE
No signature constructor using wallet connect

### ISSUE THREAD

**Issue by duyxuannguyen** [terra-money/wallet-provider#69]
Please help, how can we generate signature using wallet connection (Connect wallet mobile)?
For @terra-money/wallet-provider library, signature generation in extension is supported but wallet connection is not supported.

**Comment by iamssen** [comment]
@duyxuannguyen `sign()` and `signBytes()` are provided only by extension. walletconnect does not provide that functions.

walletconnect passes through multiple servers in the middle, so it only provides post(), a one-way request for security reasons.

**Comment by duyxuannguyen** [comment]
@iamssen my business needs to generate signature before calling post. Is there a way for me to create a signature first? Or the post function for walletconnect will create a signature
