### ISSUE TITLE
How to get cw20tokens

### ISSUE THREAD

**Issue by gwawrzak** [terra-money/wallet-provider#82]
Hi there,

I'm trying to fetch cw20tokens, however, I can't find an example, where this is actually supported.
Does this app support at all cw20tokens?

**Comment by tk-o** [comment]
I think it's not possible for a wallet provider to know all the possible CW20 tokens that a user might have.

Hence, the wallet UI allows the user adding their own tokens to the list, and then display available balances.

**Comment by gwawrzak** [comment]
Solved. We can get the balance in this way:
`    await lcd.wasm.contractQuery(contractAddress, {
        "balance": {"address": walletAddress},
    });`

**Comment by tk-o** [comment]
Thanks for including the answer 🤝
