### ISSUE TITLE
[bug] Cannot destructure property 'availableConnectTypes' of 'Object

### ISSUE THREAD

**Issue by shahzaibatzeeyotech** [terra-money/wallet-provider#9]
Hi, i'm facing an issue of destructing availableConnectTypes. i'm using v1.0.0. i tried it on Windows and Ubuntu

error:
TypeError: Cannot destructure property 'availableConnectTypes' of 'Object(...)(...)' as it is undefined.

**Comment by iamssen** [comment]
Did you set the <WalletProvider>? If react context is not provided, useWallet() returns undefined.

**Comment by shahzaibatzeeyotech** [comment]
thanks i missed WalletProvider.
